services:
  api:
    image: python:3.12-slim
    container_name: api
    working_dir: /app
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    command: >
      sh -c "pip install --no-cache-dir -r requirements.txt &&
             waitress-serve businessapi:app"
    restart: unless-stopped
  db:
    image: postgres:latest
    container_name: balance-db
    environment:
      POSTGRES_USER: postgresql
      POSTGRES_PASSWORD: postgresql
      POSTGRES_DB: balance
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: