services:
    api:
        image: python:3.12-slim
        container_name: api
        working_dir: /app
        ports:
            - "8080:8080"
        volumes:
            - .:/app
        command: >
            sh -c "pip install --no-cache-dir -r requirements.txt &&
                   waitress-serve businessapi:app"
        restart: unless-stopped