name: Deploy to Server

on:
  push:
    branches:
      - romanandr
  pull_request:
    branches:
      - romanandr

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy files to server
        run: |
          scp -o StrictHostKeyChecking=no -r . ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:${{ secrets.SERVER_DIR }}

#      - name: Run docker-compose
#        run: |
#          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "
#            cd ${{ secrets.SERVER_DIR }} &&
#            docker-compose down &&
#            docker-compose up -d
          "